"""E1 frozen explainability contract; consumer-only of Phase A–D outputs."""
from pathlib import Path
import json
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parents[1];R=ROOT/'data/research'
def run():
 rec=pd.read_csv(R/'a3_a2_replay_reconciliation.csv');risk=pd.read_csv(R/'a3_phase_b_risk_readiness.csv').drop_duplicates('opportunity_id');eco=json.loads((R/'d2_trade_economics_display_payload.json').read_text());market=json.loads((R/'c2_live_market_risk_payload.json').read_text());phasea=pd.read_csv(R/'a3_final_phase_a_risk_contract.csv')
 eco_map={x['strategy']:x for x in eco};risk= risk.rename(columns={'strategy_name':'strategy','primary_reference_available':'risk_reference_available'})
 x=rec.merge(risk[['opportunity_id','risk_reference_available','risk_reference_distance_pct','executable_stop_enabled','executable_stop_distance_pct','gap_risk_possible']],on='opportunity_id',how='left')
 x['qualification_status']='QUALIFIED';x['opportunity_priority_rank']=x.priority_rank_date_sequence;x['volume_ratio_20']='NOT_AVAILABLE';x['allocation_status']=np.where(x.a2_status.eq('ALLOCATED'),'ALLOCATED','QUALIFIED_NOT_ALLOCATED')
 code={'NORMAL_ALLOCATION':'ALLOCATED','DUPLICATE_POSITION':'DUPLICATE_POSITION','CAPITAL_CAP':'CAPITAL_CAP','CASH_CAP':'INSUFFICIENT_CASH'};x['allocation_reason_code']=x.a2_reason.map(code).fillna('OTHER_FROZEN_CONSTRAINT');x['allocation_reason_text']=x.allocation_reason_code.map({'ALLOCATED':'Allocated under frozen volume-ratio ordering and book constraints.','DUPLICATE_POSITION':'Same symbol is already open; duplicate-position protection is binding.','CAPITAL_CAP':'Maximum open-position capacity is binding.','INSUFFICIENT_CASH':'Available cash is insufficient under frozen nominal ticket policy.','OTHER_FROZEN_CONSTRAINT':'Frozen lifecycle/book constraint.'})
 x['cash_before']=x.a2_cash;x['open_positions_before']=x.a2_open_positions;x['remaining_slots_before']=x.a2_remaining_slots;x['candidate_already_open']=x.a2_duplicate
 x['reference_risk_pct_equity']=x.risk_reference_distance_pct/10;x['executable_stop_risk_pct_equity']=x.executable_stop_distance_pct/10;x['reference_heat_before_pct']='NOT_AVAILABLE';x['candidate_reference_heat_add_pct']='NOT_AVAILABLE';x['reference_heat_after_pct']='NOT_AVAILABLE';x['correlation_availability']='NOT_AVAILABLE';x['candidate_to_book_max_correlation']='NOT_AVAILABLE';x['sector_availability']='NOT_AVAILABLE';x['sector']='NOT_AVAILABLE'
 x['trade_economics_sample_source']=x.strategy.map(lambda s:eco_map.get(s,{}).get('display_sample_source','INSUFFICIENT'));x['trade_economics_sample_quality']=x.strategy.map(lambda s:eco_map.get(s,{}).get('sample_quality','LOW_SAMPLE_SIZE'));x['entry_timing_availability']='NOT_AVAILABLE';x['event_context_status']='NOT_AVAILABLE';x['market_risk_informational_only']=bool(market.get('informational_only',True));x['market_risk_level']=market.get('overall_level','NOT_AVAILABLE');x['market_risk_coverage']=market.get('source_coverage_status','INSUFFICIENT')
 x['qualification_contract_version']='FROZEN_QUALIFICATION_V1';x['phase_a_risk_contract_version']='PHASE_A_V1';x['phase_b_policy_version']='PHASE_B_V1';x['market_risk_contract_version']='C1_MARKET_RISK_CONTEXT_V1';x['trade_economics_contract_version']='D2_TRADE_ECONOMICS_V1';x['allocator_version']='REPAIRED_V2_FROZEN'
 cols=['opportunity_id','symbol','strategy','decision_date','qualification_status','opportunity_priority_rank','volume_ratio_20','allocation_status','allocation_reason_code','allocation_reason_text','cash_before','open_positions_before','remaining_slots_before','candidate_already_open','risk_reference_available','reference_risk_pct_equity','executable_stop_enabled','executable_stop_risk_pct_equity','gap_risk_possible','reference_heat_before_pct','candidate_reference_heat_add_pct','reference_heat_after_pct','correlation_availability','candidate_to_book_max_correlation','sector_availability','sector','trade_economics_sample_source','trade_economics_sample_quality','entry_timing_availability','event_context_status','market_risk_level','market_risk_coverage','market_risk_informational_only','qualification_contract_version','phase_a_risk_contract_version','phase_b_policy_version','market_risk_contract_version','trade_economics_contract_version','allocator_version']
 x[cols].to_csv(R/'e1_decision_explainability_preview.csv',index=False)
 matrix=pd.DataFrame([['Qualification','YES','NO','PREREQUISITE','NO','NO','Binding binary frozen criteria'],['Opportunity Priority','NO','YES','ORDERING_ONLY','NO','NO','Volume_Ratio_20 descending within date'],['Duplicate Position','NO','NO','YES','NO','NO','Hard constraint'],['Capital / Max Positions','NO','NO','YES','NO','NO','Hard constraint'],['Executable Stop','NO','NO','NO','NO','YES','Phase A lifecycle only'],['Trade Risk','NO','NO','NO','NO','NO','Informational except stop lifecycle'],['Portfolio Heat','NO','NO','NO','NO','NO','Informational only; no heat cap'],['Correlation / Sector','NO','NO','NO','NO','NO','Informational only'],['Entry Timing','NO','NO','NO','NO','NO','Informational only'],['Event Context','NO','NO','NO','NO','NO','Informational only'],['Market Risk','NO','NO','NO','NO','NO','Informational only'],['Trade Economics','NO','NO','NO','NO','NO','Descriptive only']],columns=['dimension','affects_qualification','affects_priority','affects_allocation','affects_sizing','affects_exit','semantics']);matrix.to_csv(R/'e1_binding_vs_informational_matrix.csv',index=False)
 reasons={'ALLOCATED':'Allocated under frozen causal volume-ratio ordering and portfolio constraints.','CAPITAL_CAP':'Qualified but not allocated because maximum positions/capital state is binding.','DUPLICATE_POSITION':'Qualified but not allocated because same symbol is already open.','INSUFFICIENT_CASH':'Qualified but not allocated because available cash is insufficient.','OTHER_FROZEN_CONSTRAINT':'Qualified but not allocated because of another existing frozen lifecycle/book constraint.'};(R/'e1_allocation_reason_contract.json').write_text(json.dumps(reasons,indent=2)+'\n')
 contract={'contract_version':'E1_DECISION_EXPLAINABILITY_V1','dimensions':['Qualification','Opportunity Priority','Portfolio Fit','Trade Risk','Portfolio Risk Impact','Entry Timing','Event Context','Market Risk Context','Trade Economics','Allocation Decision'],'human_reading_order':['Qualification','Opportunity Priority','Allocation Status','Trade Risk','Portfolio Risk Impact','Portfolio Fit','Entry Timing','Trade Economics','Event Context','Market Risk Context'],'portfolio_intelligence_contract_verdict':'PARTIAL_GO','non_binding_layers':['correlation','sector','portfolio_heat','entry_timing','event_context','market_risk_context','trade_economics'],'no_composite_score':True}
 (R/'e1_decision_dimension_contract.json').write_text(json.dumps(contract,indent=2)+'\n')
 report=['# E1 Portfolio Intelligence and Decision Explainability','', f'Preview reconciliation: **{len(x)}** canonical opportunities; **{(x.allocation_status=="ALLOCATED").sum()} allocated**, **{(x.allocation_status!="ALLOCATED").sum()} qualified-not-allocated** under corrected frozen A3 `a2_status`.', '', '## Binding vs informational matrix','',matrix.to_markdown(index=False),'','## Allocation reasons','',pd.DataFrame(reasons.items(),columns=['code','meaning']).to_markdown(index=False),'','All qualified opportunities remain visible. Correlation, sector, heat, Entry Timing, Event Context, Market Risk and Trade Economics are informational only. Sector/Event/P1 coverage remains limited, hence `PORTFOLIO_INTELLIGENCE_CONTRACT = PARTIAL_GO`; Phase E2 can consume this stable contract directly.']
 (R/'e1_portfolio_intelligence_report.md').write_text('\n'.join(report)+'\n');print({'opportunities':len(x),'allocated':int((x.allocation_status=='ALLOCATED').sum())})
if __name__=='__main__':run()
