"""P3A.1 live report; authoritative inputs are provider-injected, never fabricated."""
import os, sys
from datetime import datetime, timezone
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from event_intelligence import EventIntelligenceService
ROOT=os.path.abspath(os.path.join(os.path.dirname(__file__),"..")); OUT=os.path.join(ROOT,"data/research","p3a_1_authoritative_event_report.md")
SYMS=["RELIANCE","TCS","INFY","HDFCBANK","ICICIBANK","TATAMOTORS","SUNPHARMA","NTPC","BEL","TATASTEEL"]
def run():
    svc=EventIntelligenceService(); cs=[svc.get_context(s,datetime.now(timezone.utc)) for s in SYMS]; es=[e for c in cs for e in c['events']]; raw=sum(c['raw_item_count'] for c in cs)
    auth=[e for e in es if e['source_type'] in ('EXCHANGE_FILING','COMPANY_IR')]; news=[e for e in es if e['source_type']=='FINANCIAL_NEWS']; verified=[e for e in auth if e['materiality']!='UNKNOWN']
    examples=[]
    for c in cs[:3]:
        e=(c['events'][0] if c['events'] else {}); examples.append(f"- **{e.get('symbol','NOT_AVAILABLE')}**: {e.get('headline','No item')} | primary `{e.get('source','NOT_AVAILABLE')}` / `{e.get('source_type','NOT_AVAILABLE')}`; type `{e.get('event_type','NOT_AVAILABLE')}`; direction `{e.get('direction','UNKNOWN')}`; materiality `{e.get('materiality','UNKNOWN')}`; context `{c['event_context']}`; reaction `NOT_AVAILABLE`.")
    lines=["# P3A.1 — Authoritative Event Evidence + Materiality","",f"Generated: {datetime.now(timezone.utc).isoformat()}","","## A. Provider/source architecture","","RSS remains discovery-only. P3A.1 adds a provider-injected authoritative evidence interface for `EXCHANGE_FILING` and `COMPANY_IR`; the original document is primary and secondary items are retained as supporting sources. No authoritative provider credentials/feed were available in this run.","","## B. Source hierarchy","","NSE/BSE filing → company IR → recognised financial news → secondary. Authority governs primary-source precedence and confidence.","","## C. Event family method","","Simple symbol + event-type + normalized-headline families collapse syndicated duplicates; later members remain linked as supporting sources. The primary event is the highest-authority member.","","## D. Materiality framework","","Only an authoritative item with provider-supplied, disclosed evidence can set LOW/MEDIUM/HIGH/CRITICAL. Order value, deal terms, guidance, rating/outlook, stake or legal impact must be present; otherwise materiality is `UNKNOWN`.","","## E–F. Causality and reaction","","Events after cutoff or without a timestamp are excluded. Market reaction is `NOT_AVAILABLE` absent causal, cutoff-safe event-time price data; no priced-in claim is made.","","## G. Live coverage","",f"- 10 symbols; {raw} raw items; {len(es)} event families; deduplication {(100*(raw-len(es))/raw) if raw else 0:.1f}%.",f"- Authoritative coverage: {len(auth)}; recognised financial-news coverage: {len(news)}; verified-materiality coverage: {len(verified)}; UNKNOWN materiality: {sum(e['materiality']=='UNKNOWN' for e in es)}.","- NEW/UPDATE/DUPLICATE: all retained live discovery families are NEW; no verified update family occurred.","","## H. Representative examples","",*examples,"","## I. P3A vs P3A.1","","P3A stored headline metadata only. P3A.1 supports authoritative primary evidence, family-level supporting sources and evidence-gated materiality. This run had zero authoritative sources, so no headline interpretation was upgraded and no trading-alpha claim is made.","","## J. Limitations","","No live NSE/BSE/IR connector was configured; RSS publisher attribution is not authoritative; no causal reaction feed is attached.","","## K. Recommendation for P2A / P3B","","Add timestamped NSE/BSE and IR connectors plus immutable raw-document IDs before prospective logging and later P3B evaluation.","","# PARTIAL GO","","The cockpit can display the stricter P3A.1 contract, but `NOT_AVAILABLE`/`UNKNOWN` must remain visible until authoritative feeds are configured."]
    with open(OUT,'w') as f:f.write('\n'.join(lines)+'\n')
    print({'raw':raw,'families':len(es),'authoritative':len(auth),'verified_materiality':len(verified)})
if __name__=='__main__':run()
