"""Freeze the completed Phase B portfolio-risk contract; research-only."""
from pathlib import Path
import json
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parents[1];R=ROOT/'data/research'
POLICY={'phase_b_contract_version':'PHASE_B_V1','position_sizing_policy':'NOMINAL_FIXED_TICKET','nominal_ticket_rupees':100000,'risk_based_sizing_enabled':False,'risk_based_sizing_research_verdict':'PARTIAL_GO_NOT_PROMOTED','portfolio_heat_limit_enabled':False,'reference_risk_enabled':True,'executable_stop_risk_enabled':True,'portfolio_reference_heat_enabled':True,'portfolio_executable_stop_heat_enabled':True,'gap_risk_warning_enabled':True,'portfolio_risk_measurement_verdict':'GO'}
def run():
 rec=pd.read_csv(R/'a3_a2_replay_reconciliation.csv'); risk=pd.read_csv(R/'a3_phase_b_risk_readiness.csv').drop_duplicates('opportunity_id'); heat=pd.read_csv(R/'b1_portfolio_heat_timeseries.csv'); phase=pd.read_csv(R/'a3_final_phase_a_risk_contract.csv')
 x=rec.merge(risk,left_on='opportunity_id',right_on='opportunity_id',how='left',suffixes=('_decision','_risk')).merge(heat,left_on='decision_date',right_on='date',how='left')
 x['symbol']=x['symbol_decision']
 x['signal_id']=x.get('a3_signal_id','NOT_AVAILABLE');x['entry_date']=np.where(x.baseline_status.eq('ALLOCATED'),x.decision_date,'NOT_AVAILABLE');x['allocation_status']=x.baseline_status;x['allocation_reason']=x.baseline_reason;x['allocated_quantity']=np.where(x.allocation_status.eq('ALLOCATED'),np.floor(100000/x.entry_price),np.nan);x['position_value']=x.allocated_quantity*x.entry_price
 x['reference_risk_rupees']=x.allocated_quantity*x.risk_per_share_reference;x['reference_risk_pct_position']=x.reference_risk_rupees/x.position_value*100;x['reference_risk_pct_equity']=x.reference_risk_rupees/x.portfolio_equity*100;x['executable_risk_rupees']=x.allocated_quantity*x.risk_per_share_executable;x['executable_risk_pct_equity']=x.executable_risk_rupees/x.portfolio_equity*100
 x['reference_heat_before_rupees']=x.reference_heat_rupees;x['reference_heat_before_pct']=x.reference_heat_pct;x['executable_heat_before_pct']=x.executable_stop_heat_pct;x['candidate_reference_heat_add_rupees']=x.reference_risk_rupees.where(x.allocation_status.eq('ALLOCATED'),0);x['candidate_reference_heat_add_pct_equity']=x.candidate_reference_heat_add_rupees/x.portfolio_equity*100;x['reference_heat_after_rupees']=x.reference_heat_before_rupees+x.candidate_reference_heat_add_rupees;x['reference_heat_after_pct']=x.reference_heat_before_pct+x.candidate_reference_heat_add_pct_equity;x['executable_heat_after_pct']=x.executable_heat_before_pct+x.executable_risk_pct_equity.fillna(0);x['candidate_reference_heat_contribution_after_pct']=x.candidate_reference_heat_add_rupees/x.reference_heat_after_rupees*100
 x['risk_availability_status']=np.where(x.primary_reference_available,'AVAILABLE','RISK_REFERENCE_NOT_AVAILABLE');x['risk_contract_version']='PHASE_A_V1'
 for k,v in POLICY.items():x[k]=v
 cols=['opportunity_id','signal_id','symbol','strategy','decision_date','entry_date','allocation_status','allocation_reason','allocated_quantity','position_value','primary_reference_type','primary_reference_value','primary_reference_available','risk_per_share_reference','reference_risk_rupees','reference_risk_pct_position','reference_risk_pct_equity','executable_stop_enabled','initial_executable_stop','risk_per_share_executable','executable_risk_rupees','executable_risk_pct_equity','defined_risk_type','gap_risk_possible','portfolio_equity','cash','open_positions','reference_heat_before_rupees','reference_heat_before_pct','reference_heat_after_rupees','reference_heat_after_pct','executable_heat_before_pct','executable_heat_after_pct','risk_availability_status','candidate_reference_heat_add_rupees','candidate_reference_heat_add_pct_equity','candidate_reference_heat_contribution_after_pct','position_sizing_policy','nominal_ticket_rupees','risk_based_sizing_enabled','portfolio_heat_limit_enabled','risk_contract_version','phase_b_contract_version']
 x[cols].to_csv(R/'b3_canonical_portfolio_risk_lineage.csv',index=False)
 summary=pd.DataFrame([{'portfolio_equity':heat.portfolio_equity.iloc[-1],'cash':'NOT_AVAILABLE','deployed_capital':heat.deployed_capital.mean(),'open_positions':heat.open_positions.mean(),'reference_heat_rupees':heat.reference_heat_rupees.mean(),'reference_heat_pct':heat.reference_heat_pct.mean(),'executable_stop_heat_rupees':heat.executable_stop_heat_rupees.mean(),'executable_stop_heat_pct':heat.executable_stop_heat_pct.mean(),'largest_position_reference_risk_rupees':x.reference_risk_rupees.max(),'largest_position_reference_heat_contribution_pct':x.candidate_reference_heat_contribution_after_pct.max(),'positions_without_valid_reference':(~x.primary_reference_available.fillna(False)).sum(),'reference_heat_coverage_count':x.primary_reference_available.fillna(False).sum(),'reference_heat_missing_count':(~x.primary_reference_available.fillna(False)).sum()}]);summary.to_csv(R/'b3_portfolio_risk_summary.csv',index=False)
 (R/'b3_phase_b_policy_contract.json').write_text(json.dumps(POLICY,indent=2)+'\n')
 report=['# B3 Phase B Freeze','', '## Active policy','', '₹1,00,000 nominal fixed tickets; risk-based sizing disabled; no portfolio heat limit.','', '## Preserved B2 evidence','', 'Reference-risk sizing compressed tail risk/heat and improved drawdown, but degraded total return, Sharpe and utilization. It remains `PARTIAL_GO_NOT_PROMOTED`.','', '## Semantics','', 'Reference risk is strategy-specific downside context and may not be an executable stop. Executable-stop risk is defined normal-stop exposure; gaps can exceed it. Reference heat includes available references; executable-stop heat is supplementary and excludes non-stop positions.','', '## Final verdicts','', '`PORTFOLIO_RISK_MEASUREMENT = GO`; `RISK_BASED_SIZING = PARTIAL_GO_NOT_PROMOTED`; `PHASE B = COMPLETE`.','', 'True NR7 reference coverage remains partial; missing reference positions are explicitly counted, never silently zeroed.']
 (R/'b3_phase_b_freeze_report.md').write_text('\n'.join(report)+'\n');print({'lineage_rows':len(x),'missing_reference':int((~x.primary_reference_available.fillna(False)).sum())})
if __name__=='__main__':run()
