"""P4.3 canonical point-in-time ledger; research-only, no live mutation."""
import os,sys,pickle,pandas as pd,numpy as np
sys.path.insert(0,os.path.abspath(os.path.join(os.path.dirname(__file__),'..')))
from adapters import SECTOR_MAP
ROOT=os.path.abspath(os.path.join(os.path.dirname(__file__),'..')); P1=os.path.join(ROOT,'data/research/p1_qualified_signals.csv'); EXP=os.path.join(ROOT,'data/ml/step_6/expanded_strategy_dataset.csv'); OUT=os.path.join(ROOT,'data/research')
def run():
 p=pd.read_csv(P1); e=pd.read_csv(EXP)[['signal_date','symbol','strategy_name','entry_date','entry_price','composite_score']]
 d=p.merge(e,on=['signal_date','symbol','strategy_name'],how='left',suffixes=('','_expanded')); d['sector']=d.symbol.map(SECTOR_MAP); d['sector_source']=np.where(d.sector.notna(),'STATIC_PROJECT_MAP','NOT_AVAILABLE'); d['sector_available']=d.sector.notna(); d['stop_loss']=np.nan; d['stop_source']='NOT_AVAILABLE'; d['stop_available']=False; d['qualification_status']='QUALIFIED'; d['data_as_of']=d.signal_date; d['opportunity_priority']=d.composite_score.fillna(d.volume_ratio_20); d['capital_available_before']=1000000.; d['open_positions_before']='NOT_AVAILABLE'; d['existing_same_symbol_flag']=False; d['historical_return_window_available']=False; d['causal_60d_returns_reference']='NOT_AVAILABLE'; d['risk_per_share']='NOT_AVAILABLE'; d['position_risk_inr']='NOT_AVAILABLE'
 # preserve strategy rows; allocation consolidates same symbol/date to highest causal priority
 d['contributing_strategies']=d.groupby(['signal_date','symbol'])['strategy_name'].transform(lambda x:' | '.join(sorted(x.unique())))
 d['is_unique_opportunity']=d.groupby(['signal_date','symbol']).opportunity_priority.rank(method='first',ascending=False).eq(1)
 d.to_csv(os.path.join(OUT,'p4_3_canonical_portfolio_ledger.csv'),index=False)
 cov={'strategy_signal_n':len(d),'unique_symbol_date_n':int(d.is_unique_opportunity.sum()),'sector_known_n':int(d.sector_available.sum()),'sector_missing_n':int((~d.sector_available).sum()),'genuine_stop_n':0,'causal_correlation_n':0}
 report=['# P4.3A + P4.3B — Canonical Portfolio Ledger + Robust Shadow Allocation','','## A–C. Ledger and coverage','',f'- Coverage: {cov}.','- Each row is a strategy-level qualified opportunity; allocation must consolidate same symbol/date to highest existing causal opportunity priority while retaining contributing strategies.','- Sector is only the existing static project map; unknown sectors remain NOT_AVAILABLE. Stops are unavailable in this contract, so heat control is NOT RUN.','','## D–I. Shadow controls','', 'Baseline, sector, correlation and heat re-tests are NOT RUN as equivalent frozen execution requires causal open-book state and genuine stops. Correlation can only be added after validating the cached OHLCV symbol/date contract against this ledger. No future returns were used in ledger fields.','','## J–N. Status, examples, limitations and recommendation','', d[['symbol','signal_date','strategy_name','opportunity_priority','sector','sector_available','stop_available','is_unique_opportunity','contributing_strategies']].head(5).to_markdown(index=False),'','P4 live integration remains blocked: the canonical ledger establishes reconciliation and explicit missingness, but does not manufacture historical stops/open-book/correlation evidence. P4.4 should validate OHLCV date coverage and reconstruct frozen simulator open positions before retesting controls.','','# NO-GO']
 open(os.path.join(OUT,'p4_3_portfolio_intelligence_report.md'),'w').write('\n'.join(report)+'\n'); print(cov)
if __name__=='__main__':run()
