"""D0 local/free-data foundation inventory; preserves all raw/frozen inputs."""
import os,sys,pickle,hashlib,pandas as pd,numpy as np
sys.path.insert(0,os.path.abspath(os.path.join(os.path.dirname(__file__),'..')))
from adapters import SECTOR_MAP
ROOT=os.path.abspath(os.path.join(os.path.dirname(__file__),'..')); F=os.path.join(ROOT,'data/foundation'); CACHE=os.path.join(ROOT,'data/ml/step_6/cached_ohlcv_indicators.pkl'); LEDGER=os.path.join(ROOT,'data/research/p4_3_canonical_portfolio_ledger.csv')
def run():
 os.makedirs(F,exist_ok=True); cache=pickle.load(open(CACHE,'rb')); rows=[]; master=[]
 for sym,x in cache.items():
  x=x.copy(); x.index=pd.to_datetime(x.index); master.append({'security_id':'LOCAL_'+sym,'NSE_symbol':sym,'ISIN':'NOT_AVAILABLE','BSE_code':'NOT_AVAILABLE','company_name':'NOT_AVAILABLE','valid_from':str(x.index.min().date()),'valid_to':str(x.index.max().date()),'source':'cached_ohlcv_indicators.pkl','confidence':'UNVERIFIED'})
  for dt,r in x.iterrows(): rows.append({'security_id':'LOCAL_'+sym,'symbol':sym,'date':str(dt.date()),'open':r.Open,'high':r.High,'low':r.Low,'close':r.Close,'volume':r.Volume,'turnover':'NOT_AVAILABLE','number_of_trades':'NOT_AVAILABLE','trading_status':'NOT_AVAILABLE','source':'local_cache','adjustment_status':'UNKNOWN'})
 o=pd.DataFrame(rows); o.to_csv(os.path.join(F,'daily_ohlcv.csv'),index=False); pd.DataFrame(master).to_csv(os.path.join(F,'security_master.csv'),index=False)
 l=pd.read_csv(LEDGER); dates=pd.to_datetime(l.signal_date); idx={(s,pd.Timestamp(d).normalize()) for s,x in cache.items() for d in pd.to_datetime(x.index)}
 pos={(s,pd.Timestamp(d).normalize()):i for s,x in cache.items() for i,d in enumerate(pd.to_datetime(x.index))}; l['ohlcv_t_available']=[(s,pd.Timestamp(d)) in pos for s,d in zip(l.symbol,dates)]; l['ohlcv_20d_available']=[pos.get((s,pd.Timestamp(d)),-1)>=20 for s,d in zip(l.symbol,dates)]; l['ohlcv_60d_available']=[pos.get((s,pd.Timestamp(d)),-1)>=60 for s,d in zip(l.symbol,dates)]
 l['sector']=l.symbol.map(SECTOR_MAP); l['sector_available']=l.sector.notna(); l['sector_source']=np.where(l.sector_available,'STATIC_PROJECT_MAP','NOT_AVAILABLE'); l['stop_available']=False; l['stop_loss']='NOT_AVAILABLE'; l['historical_return_window_available']=l.ohlcv_60d_available; l.to_csv(os.path.join(F,'canonical_opportunity_ledger.csv'),index=False)
 bad=((o.high<o[['open','close','low']].max(axis=1))|(o.low>o[['open','close','high']].min(axis=1))|(o[['open','high','low','close']]<=0).any(axis=1)).sum(); cov={'OHLCV':'READY','corporate_actions':'PARTIAL','security_master':'PARTIAL','PIT_universe':'PARTIAL','sector':'PARTIAL','delivery':'BLOCKED','portfolio_state':'PARTIAL','genuine_stops':'BLOCKED','lineage':'PARTIAL'}
 manifest=pd.DataFrame([{'dataset_name':'daily_ohlcv','source':'local cache','row_count':len(o),'symbol_count':o.symbol.nunique(),'date_min':o.date.min(),'date_max':o.date.max(),'duplicate_count':int(o.duplicated(['security_id','date']).sum()),'missingness':int(o.isna().sum().sum()),'adjustment_status':'UNKNOWN','PIT_status':'LOCAL_CACHE','confidence':'UNVERIFIED','known_limitations':'80 symbols only; adjustment state unknown'}, {'dataset_name':'delivery','source':'none','row_count':0,'symbol_count':0,'date_min':'NOT_AVAILABLE','date_max':'NOT_AVAILABLE','duplicate_count':0,'missingness':'NOT_AVAILABLE','adjustment_status':'NOT_AVAILABLE','PIT_status':'NOT_AVAILABLE','confidence':'UNVERIFIED','known_limitations':'DEFERRED_FREE_SOURCE_LIMITATION'}]); manifest.to_csv(os.path.join(F,'data_coverage_manifest.csv'),index=False)
 report=['# D0 — Free Data Foundation + Causal Reconstruction','','## A–C. Inventory and OHLCV','',f'- Local cache: {len(o)} OHLCV rows / {o.symbol.nunique()} symbols / {o.date.min()} to {o.date.max()}; duplicate security/date {o.duplicated(["security_id","date"]).sum()}, invalid OHLC rows {bad}.','- P4 ledger: T/20D/60D coverage {l.ohlcv_t_available.sum()}/{l.ohlcv_20d_available.sum()}/{l.ohlcv_60d_available.sum()} of {len(l)} strategy signals; coverage is local-cache-only and not a claim of complete NIFTY 500 history.','','## D–L. Foundation status','', '- Corporate actions: PARTIAL; cache adjustment state UNKNOWN, with dividend/split columns preserved but no authoritative action ledger.', '- Security/symbol: PARTIAL; local permanent IDs and history bounds created, ISIN/BSE continuity unavailable.', '- PIT universe: PARTIAL; existing universe_engine reconstruction retained, not replaced.',f'- Sector: {l.sector_available.sum()}/{len(l)} known through static current project map; unknown remains NOT_AVAILABLE.','- Delivery: BLOCKED / DEFERRED_FREE_SOURCE_LIMITATION.','- Portfolio state: PARTIAL; frozen simulator semantics exist, but no full causal open-book replay was emitted in D0.', '- Genuine stops: BLOCKED; none fabricated.','- Lineage: PARTIAL; strategy/symbol/date opportunity consolidation remains 1,009 signals → 526 unique opportunities.','','## M–P. Readiness and impact','',f'- Domains: {cov}.','- Step 8, Step 10C, P1, P2A: UNCHANGED (no raw prices/frozen artifacts overwritten). P4: MINOR DATA DIFFERENCE—new explicit local OHLCV/sector availability, no allocation rerun.','- Overall: **PARTIAL READY** for core local-cache research; P4 risk/correlation and delivery/event research remain blocked.']
 open(os.path.join(ROOT,'data/research/d0_free_data_foundation_report.md'),'w').write('\n'.join(report)+'\n'); print(cov)
if __name__=='__main__':run()
