"""D0.1A auditable opportunity-to-frozen-trade identity bridge."""
import os,sys,hashlib,pandas as pd,numpy as np
ROOT=os.path.abspath(os.path.join(os.path.dirname(__file__),'..')); P4=os.path.join(ROOT,'data/research/p4_3_canonical_portfolio_ledger.csv'); TR=os.path.join(ROOT,'data/mvp/trade_ledger.csv'); F=os.path.join(ROOT,'data/foundation'); R=os.path.join(ROOT,'data/research')
def sym(x): return str(x).replace('.NS','').strip().upper()
def strat(x): return str(x).strip()
def run():
 p=pd.read_csv(P4); t=pd.read_csv(TR); p['symbol_n']=p.symbol.map(sym); p['strategy_n']=p.strategy_name.map(strat); t['symbol_n']=t.symbol.map(sym); t['strategy_n']=t.strategy_name.map(strat)
 p['opportunity_id']=p.apply(lambda r:'OPP_'+hashlib.sha1(f"{r.symbol_n}|{r.signal_date}".encode()).hexdigest()[:14],axis=1); p['security_id']='LOCAL_'+p.symbol_n
 # highest existing causal priority represents the unique allocatable opportunity
 u=p.sort_values('opportunity_priority',ascending=False).drop_duplicates(['symbol_n','signal_date'],keep='first').copy(); contrib=p.groupby(['symbol_n','signal_date']).strategy_name.apply(lambda x:' | '.join(sorted(x.unique()))).to_dict(); u['contributing_strategies']=[contrib[(r.symbol_n,r.signal_date)] for _,r in u.iterrows()]
 keys=['symbol_n','signal_date','strategy_n']; counts=t.groupby(keys).size().to_dict(); matches=[]; used=set()
 for _,r in u.iterrows():
  cand=t[(t.symbol_n==r.symbol_n)&(t.signal_date.astype(str)==str(r.signal_date))&(t.strategy_n==r.strategy_n)]
  if len(cand)==1:
   q=cand.iloc[0]; used.add(q.name); status='MATCHED_EXACT'; conf='1.0'; reason='symbol + signal_date + strategy unique match'; diff=round(float(q.entry_price)-float(r.entry_price),4) if pd.notna(r.entry_price) else np.nan; dc='EXPECTED_EXECUTION_SEMANTIC' if pd.notna(diff) else 'NOT_AVAILABLE'
  elif len(cand)>1: q=None; status='AMBIGUOUS'; conf='0'; reason='multiple frozen trades share identity'; diff=np.nan; dc='NOT_AVAILABLE'
  else: q=None; status='UNMATCHED_NOT_ALLOCATED'; conf='0'; reason='no frozen trade with causal identity'; diff=np.nan; dc='NOT_AVAILABLE'
  matches.append({'opportunity_id':r.opportunity_id,'security_id':r.security_id,'symbol':r.symbol_n,'signal_date':r.signal_date,'strategy':r.strategy_n,'contributing_strategies':r.contributing_strategies,'execution_id':('TRD_'+str(q.name) if q is not None else 'NOT_AVAILABLE'),'execution_date':(q.entry_date if q is not None else 'NOT_AVAILABLE'),'entry_price':(q.entry_price if q is not None else np.nan),'exit_date':(q.exit_date if q is not None else 'NOT_AVAILABLE'),'match_status':status,'match_confidence':conf,'match_reason':reason,'timing_semantic':'T signal -> T+1 Open (frozen simulator)','price_difference':diff,'difference_class':dc})
 b=pd.DataFrame(matches); b.to_csv(os.path.join(F,'opportunity_execution_bridge.csv'),index=False); exec_side=t.copy(); exec_side['execution_status']=['MATCHED_TO_OPPORTUNITY' if i in used else 'EXECUTION_ONLY' for i in t.index]; exec_side.to_csv(os.path.join(F,'execution_opportunity_reconciliation.csv'),index=False)
 report=['# D0.1A — Opportunity ↔ Execution Identity Reconciliation','','## A–E. Contracts and method','', f'- P4: {len(p)} strategy rows → {len(u)} unique symbol/date opportunities. Frozen MVP trade ledger: {len(t)} trades.','- Normalization: uppercase bare NSE symbols, exact strategy labels, ISO signal date. Match uses symbol + signal date + strategy only; no future outcomes.','- Timing semantic: frozen simulator uses signal T → entry T+1 Open; entry-price variance is labelled expected semantic, not a match key.','','## F–G. Reconciliation','',b.match_status.value_counts().rename_axis('status').reset_index(name='count').to_markdown(index=False),'',exec_side.execution_status.value_counts().rename_axis('status').reset_index(name='count').to_markdown(index=False),'','## H. Root cause','', 'P4 is the later volume/EMA-qualified P1 population; the frozen MVP trade ledger reflects its own historical signal population and allocation lifecycle. Unmatched P4 opportunities cannot be assumed capital-capped.','','## I–J. Examples','',b.head(10).to_markdown(index=False),'','## K–L. Replay readiness','', '# REPLAY_PARTIAL','', 'D0.1B should reconstruct state only over matched frozen execution rows, then attach it to P4 opportunities as informational `CONTRACT_GAP` where no causal bridge exists; do not claim an exact full-P4 replay.']
 open(os.path.join(R,'d0_1a_opportunity_execution_reconciliation_report.md'),'w').write('\n'.join(report)+'\n'); print({'unique':len(u),'trades':len(t),'matches':b.match_status.value_counts().to_dict(),'exec':exec_side.execution_status.value_counts().to_dict()})
if __name__=='__main__':run()
